export const IllegalWordsArray: string[] = [
  "Idiot",
  "idiot",
  "Arschloch",
  "arschloch",
  "Bastard",
  "bastard",
  "Dummkopf",
  "dummkopf",
  "Spast",
  "spast",
  "Wichser",
  "wichser",
  "Hurensohn",
  "hurensohn",
  "Blödmann",
  "blödmann",
  "Penner",
  "penner",
  "Opfer",
  "opfer",
  "Vollidiot",
  "vollidiot",
  "Vollidioten",
  "vollidioten",
  "Schwachkopf",
  "schwachkopf",
  "Lappen",
  "lappen",
  "fick dich",
  "fuck you",
  "Mongo",
  "mongo",
  "Missgeburt",
  "Missgeburten",
  "missgeburt",
  "missgeburten",
  "scheiß Hure",
  "Schlampe",
  "schalmpe",
  "Drecksack",
  "drecksack",
  "Drecksäcke",
  "drecksäcke",
  "dreckige Jude",
  "scheis Jude",
  "scheiß Jude",
  "drecks Jude",
  "Drecks Jude",
  "dreckigen Juden",
  "scheis Juden",
  "scheiß Juden",
  "drecks Juden",
  "Drecks Juden",
  "dreckiger Moslem",
  "scheis Moslem",
  "scheiß Moslem",
  "drecks Moslem",
  "Drecks Moslem",
  "dreckige Moslems",
  "scheis Moslems",
  "scheiß Moslems",
  "drecks Moslems",
  "Drecks Moslems",
  "Moslempack",
  "dreckiger Asylant",
  "scheis Asylant",
  "scheiß Asylant",
  "drecks Asylant",
  "Drecks Asylant",
  "dreckige Asylanten",
  "scheis Asylanten",
  "scheiß Asylanten",
  "drecks Asylanten",
  "Drecks Asylanten",
  "dreckiger Migrant",
  "scheis Migrant",
  "scheiß Migrant",
  "drecks Migrant",
  "Drecks Migrant",
  "dreckiger Migrant",
  "scheis Migranten",
  "scheiß Migranten",
  "drecks Migranten",
  "Drecks Migranten",
  "dreckiger Flüchtling",
  "scheis Flüchtling",
  "scheiß Flüchtling",
  "drecks Flüchtling",
  "Drecks Flüchtling",
  "dreckige Flüchtlinge",
  "scheis Flüchtlinge",
  "scheiß Flüchtlinge",
  "drecks Flüchtlinge",
  "Drecks Flüchtlinge",
  "scheis Schwarzer",
  "scheiß Schwarzer",
  "drecks Schwarzer",
  "Drecks Schwarzer",
  "scheis Schwarze",
  "scheiß Schwarze",
  "drecks Schwarze",
  "Drecks Schwarze",
  "scheis Türke",
  "scheiß Türke",
  "drecks Türke",
  "Drecks Türcke",
  "scheis Türken",
  "scheis Türken",
  "drecks Türken",
  "Drecks Türken",
  "scheis Faschist",
  "scheiß Faschist",
  "drecks Faschist",
  "Drecks Faschist",
  "scheis Faschisten",
  "scheiß Faschisten",
  "drecks Faschisten",
  "drecks Faschisten",
  "Faschistenschwein",
  "Faschistenschweine",
  "scheis Nazi",
  "scheiß Nazi",
  "drecks Nazi",
  "Drecks Nazi",
  "scheis Nazis",
  "scheiß Nazis",
  "drecks Nazis",
  "Drecks Nazis",
  "Japse",
  "japse",
  "Dorftrottel",
  "dorftrottel",
  "Japsen",
  "japsen",
  "scheis Latino",
  "scheiß Latino",
  "drecks Latino",
  "Drecks Latino",
  "scheis Latinos",
  "scheiß Latinos",
  "drecks Latinos",
  "Drecks Latinos",
  "scheis Latina",
  "scheiß Latina",
  "drecks Latina",
  "Drecks Latina",
  "scheis Latinas",
  "scheiß Latinas",
  "drecks Latinas",
  "Drecks Latinas",
  "so ein scheis Spaghetti",
  "so ein scheiß Spaghetti",
  "Du bist ein scheis Spaghetti",
  "Du bist ein scheiß Spaghetti",
  "so ein drecks Spaghetti",
  "so ein Drecks Spaghetti",
  "Du bist ein drecks Spaghetti",
  "Du bist ein Drecks Spaghetti",
  "Schlitzauge",
  "schlitzauge",
  "Schlappschwatz",
  "schlappschwatz",
  "Schlapschwatz",
  "schlapschwatz",
  "scheis Rechter",
  "scheiß Rechter",
  "drecks Rechter",
  "Drecks Rechter",
  "scheis Deutscher",
  "scheiß Deutscher",
  "dreckige Deutscher",
  "Drecks Deutscher",
  "drecks Deutscher",
  "scheis Deutsche",
  "scheiß Deutsche",
  "drecks Deutsche",
  "Drecks Deutsche",
  "dreckige Deutsche",
  "Schlitzaugen",
  "schlitzaugen",
  "Vollhorst",
  "vollhorst",
  "Polake",
  "Polaken",
  "polake",
  "polaken",
  "Untermensch",
  "untermensch",
  "Abschaum",
  "abschaum",
  "Neger",
  "Kanake",
  "Kanaken",
  "kanake",
  "kanaken",
  "Nazi",
  "Nazi-Schlampe",
  "Nazischlampe",
  "nazi",
  "nazi-Schlampe",
  "nazischlampe",
  "Rassist",
  "Abschaum",
  "Rassistenschwein",
  "Rassistenschweine",
  "rassist",
  "abschaum",
  "rassistenschwein",
  "rassistenschweine",
  "scheis Fundamentalist",
  "scheiß Fundamentalist",
  "drecks Fundamentalist",
  "Drecks Fundamentalist",
  "scheis Fundamentalisten",
  "scheiß Fundamentalisten",
  "drecks Fundamentalisten",
  "Drecks Fundamentalisten",
  "scheis Extremist",
  "scheiß Extremist",
  "drecks Extremist",
  "Drecks Extremist",
  "scheis Extremisten",
  "scheiß Extremisten",
  "drecks Extremisten",
  "Drecks Extremisten",
  "scheis Rechtsextremist",
  "scheiß Rechtsextremist",
  "drecks Rechtsextremist",
  "Drecks Rechtsextremist",
  "dreckiger Rechtsextremist",
  "scheis Rechtsextremisten",
  "scheiß Rechtsextremisten",
  "drecks Rechtsextremisten",
  "Drecks Rechtsextremisten",
  "dreckigen Rechtsextremisten",
  "scheis Lesbe",
  "scheiß Lesbe",
  "drecks Lesbe",
  "Drecks Lsebe",
  "dreckige Lesbe",
  "scheis Lesben",
  "scheiß Lesben",
  "drecks Lesben",
  "Drecks Lesben",
  "dreckige Lesben",
  "Weib",
  "weib",
  "Weibsbild",
  "weibsbild",
  "Heil Hilter",
  "Sieg Heil",
  "mein Führer",
  "Mein Führer",
  "Heil mein Führer",
  "scheis Tunte",
  "scheiß Tunte",
  "drecks Tunte",
  "Drecks Tunte",
  "dreckige Tunte",
  "scheis Tunten",
  "scheiß Tunten",
  "drecks Tunten",
  "Drecks Tunten",
  "dreckigen Tunten",
  "scheiß Fanatiker",
  "scheis Fanatiker",
  "drecks Fanatiker",
  "Drecks Fanatiker",
  "dreckiger Islamist",
  "dreckigen Islamisten",
  "scheis Islamist",
  "scheiß Islamist",
  "drecks Islamist",
  "Drecks Islamist",
  "scheis Islamisten",
  "scheiß Islamisten",
  "drecks Islamisten",
  "Drecks Islamisten",
  "scheis Terrorist",
  "scheiß Terrorist",
  "drecks Terrorist",
  "Drecks Terrorist",
  "scheis Terroristen",
  "scheiß Terroristen",
  "drecks Terrorsiten",
  "Drecks Terrorsiten",
  "blöde Tussi",
  "scheis Tussi",
  "scheiß Tussi",
  "drecks Tussi",
  "Drecks Tussi",
  "Schwuchtel",
  "Schwuchteln",
  "scheis Homo",
  "scheiß Homo",
  "drecks Homo",
  "Drecks Homo",
  "dreckiger Homo",
  "scheis Homos",
  "scheiß Homos",
  "drecks Homos",
  "Drecks Homos",
  "dreckigen Homos",
  "Trulla",
  "Versager",
  "Krüppel",
  "Dreckspack",
  "Krüppel",
  "Psychopath",
  "Behindie",
  "trulla",
  "versager",
  "krüppel",
  "dreckspack",
  "krüppel",
  "psychopath",
  "behindie",
];
